# Empezamos desde la imagen de GROBID que deseas utilizar
FROM lfoppiano/grobid:0.7.1

# Aquí puedes añadir pasos adicionales para personalizar tu imagen,
# como instalar dependencias adicionales, copiar archivos, etc.
